### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by noy98** [EntryPointKR/SpicordOld#1]
[00:11:34] [SpicordThread/WARN]: [Spicord] Exception!
kr.entree.spicord.libs.jda.api.exceptions.HierarchyException: Can't modify a member with higher or equal highest role than yourself!
        at kr.entree.spicord.libs.jda.internal.entities.GuildImpl.checkPosition(GuildImpl.java:1220) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.libs.jda.internal.entities.GuildImpl.modifyNickname(GuildImpl.java:816) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.libs.jda.api.entities.Member.modifyNickname(Member.java:587) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.handler.Rename.accept(Rename.java:23) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.handler.Rename.accept(Rename.java:13) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.handler.GuildMemberHandler.lambda$createTask$0(GuildMemberHandler.java:30) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.handler.GuildMemberHandler.accept(GuildMemberHandler.java:42) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.handler.GuildMemberHandler.accept(GuildMemberHandler.java:15) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.task.guild.GuildTask.handle(GuildTask.java:29) ~[Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.Discord.takeAndNotifyConsumer(Discord.java:90) [Spicord-1.1.1.jar:?]
        at kr.entree.spicord.discord.Discord.run(Discord.java:41) [Spicord-1.1.1.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by entrypointkr** [comment]
config.yml 에 verification 부분 discord-role 에 적힌 역할이 디스코드 봇이 가진 역할보다 상위에 있어서 생긴 문제입니다
![image](https://user-images.githubusercontent.com/16044565/70099808-41d8d180-1673-11ea-850f-fe48ed6d9c10.png)
위 이미지처럼 봇 역할이 상위에 있도록 조정해주세요
