### ISSUE TITLE
폴더 생성이 안됨 + 오류

### ISSUE THREAD

**Issue by SopiB** [EntryPointKR/SpicordOld#2]
00:09:14 [심각] Error occurred while enabling Spicord v1.2.0 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins\spicord-legacy-1.2.0.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:149)
        at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:137)
        at kr.entree.spicord.Spicord.onEnable(Spicord.java:56)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:382)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:284)
        at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:266)
        at net.minecraft.server.v1_5_R3.MinecraftServer.j(MinecraftServer.java:310)
        at net.minecraft.server.v1_5_R3.MinecraftServer.e(MinecraftServer.java:289)
        at net.minecraft.server.v1_5_R3.MinecraftServer.a(MinecraftServer.java:249)
        at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:158)
        at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)

**Comment by entrypointkr** [comment]
Fix: 64f2942
